-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Wed Aug 19 11:02:43 2026
-- Host        : ams34 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim
--               D:/Chip2026/Chip2026_Testing/CHIP2026_TestingSetup.srcs/sources_1/bd/design_1/ip/design_1_TO_FMC_0_0/design_1_TO_FMC_0_0_sim_netlist.vhdl
-- Design      : design_1_TO_FMC_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity design_1_TO_FMC_0_0 is
  port (
    BANK_EN : in STD_LOGIC_VECTOR ( 3 downto 0 );
    WL_EN : in STD_LOGIC;
    SA_EN : in STD_LOGIC;
    BL_PCHG : in STD_LOGIC;
    CLK_SA : in STD_LOGIC;
    WRITE_EN : in STD_LOGIC;
    CS : in STD_LOGIC_VECTOR ( 1 downto 0 );
    SCN_SEL : in STD_LOGIC_VECTOR ( 3 downto 0 );
    CLK_A : in STD_LOGIC;
    CLK_B : in STD_LOGIC;
    IN_EN : in STD_LOGIC;
    SCN_IN : in STD_LOGIC;
    InputEN_DAC : in STD_LOGIC;
    CALIB_EN : in STD_LOGIC;
    BANK_SEL : in STD_LOGIC;
    CHG_EN : in STD_LOGIC;
    RST_CAP_B : in STD_LOGIC;
    VDAC_CTRL : in STD_LOGIC;
    VTC_EN : in STD_LOGIC;
    TDC_EN : in STD_LOGIC;
    TDC_RST : in STD_LOGIC;
    TDC_COMPUTE : in STD_LOGIC;
    DFF_RST : in STD_LOGIC;
    CTRL_EN : in STD_LOGIC;
    CTRL_VB : in STD_LOGIC;
    CTRL_VBP : in STD_LOGIC;
    CTRL_VBN : in STD_LOGIC;
    FMC_L21 : out STD_LOGIC;
    FMC_L22 : out STD_LOGIC;
    FMC_R19 : out STD_LOGIC;
    FMC_T19 : out STD_LOGIC;
    FMC_K19 : out STD_LOGIC;
    FMC_K20 : out STD_LOGIC;
    FMC_D20 : out STD_LOGIC;
    FMC_C20 : out STD_LOGIC;
    FMC_E21 : out STD_LOGIC;
    FMC_D21 : out STD_LOGIC;
    FMC_N19 : out STD_LOGIC;
    FMC_N20 : out STD_LOGIC;
    FMC_J18 : out STD_LOGIC;
    FMC_K18 : out STD_LOGIC;
    FMC_R20 : out STD_LOGIC;
    FMC_R21 : out STD_LOGIC;
    FMC_L17 : out STD_LOGIC;
    FMC_M17 : out STD_LOGIC;
    FMC_B19 : out STD_LOGIC;
    FMC_B20 : out STD_LOGIC;
    FMC_E15 : out STD_LOGIC;
    FMC_D15 : out STD_LOGIC;
    FMC_F18 : out STD_LOGIC;
    FMC_E18 : out STD_LOGIC;
    FMC_M19 : out STD_LOGIC;
    FMC_M20 : out STD_LOGIC;
    FMC_N22 : out STD_LOGIC;
    FMC_P22 : out STD_LOGIC;
    FMC_J21 : out STD_LOGIC;
    FMC_J22 : out STD_LOGIC;
    FMC_G20 : out STD_LOGIC;
    FMC_G21 : out STD_LOGIC;
    FMC_G19 : out STD_LOGIC;
    FMC_F19 : out STD_LOGIC;
    FMC_D22 : out STD_LOGIC;
    FMC_C22 : out STD_LOGIC;
    FMC_B16 : out STD_LOGIC;
    FMC_B17 : out STD_LOGIC;
    FMC_B21 : out STD_LOGIC;
    FMC_B22 : out STD_LOGIC;
    FMC_C17 : in STD_LOGIC;
    FMC_C18 : in STD_LOGIC;
    DIG_AXI_OUT_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    DIG_DEBUG_AXI_OUT_0 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    DIG_DEBUG_AXI_OUT_1 : out STD_LOGIC_VECTOR ( 1 downto 0 )
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of design_1_TO_FMC_0_0 : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_1_TO_FMC_0_0 : entity is "design_1_TO_FMC_0_0,TO_FMC,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_1_TO_FMC_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of design_1_TO_FMC_0_0 : entity is "module_ref";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of design_1_TO_FMC_0_0 : entity is "TO_FMC,Vivado 2018.3";
end design_1_TO_FMC_0_0;

architecture STRUCTURE of design_1_TO_FMC_0_0 is
  signal \^bank_en\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^bank_sel\ : STD_LOGIC;
  signal \^bl_pchg\ : STD_LOGIC;
  signal \^calib_en\ : STD_LOGIC;
  signal \^chg_en\ : STD_LOGIC;
  signal \^clk_a\ : STD_LOGIC;
  signal \^clk_b\ : STD_LOGIC;
  signal \^clk_sa\ : STD_LOGIC;
  signal \^cs\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^ctrl_en\ : STD_LOGIC;
  signal \^ctrl_vb\ : STD_LOGIC;
  signal \^ctrl_vbn\ : STD_LOGIC;
  signal \^ctrl_vbp\ : STD_LOGIC;
  signal \^dff_rst\ : STD_LOGIC;
  signal \^fmc_c17\ : STD_LOGIC;
  signal \^fmc_c18\ : STD_LOGIC;
  signal \^in_en\ : STD_LOGIC;
  signal \^inputen_dac\ : STD_LOGIC;
  signal \^rst_cap_b\ : STD_LOGIC;
  signal \^sa_en\ : STD_LOGIC;
  signal \^scn_in\ : STD_LOGIC;
  signal \^scn_sel\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^tdc_compute\ : STD_LOGIC;
  signal \^tdc_en\ : STD_LOGIC;
  signal \^tdc_rst\ : STD_LOGIC;
  signal \^vdac_ctrl\ : STD_LOGIC;
  signal \^vtc_en\ : STD_LOGIC;
  signal \^wl_en\ : STD_LOGIC;
  signal \^write_en\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of DFF_RST : signal is "xilinx.com:signal:reset:1.0 DFF_RST RST";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of DFF_RST : signal is "XIL_INTERFACENAME DFF_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of TDC_RST : signal is "xilinx.com:signal:reset:1.0 TDC_RST RST";
  attribute X_INTERFACE_PARAMETER of TDC_RST : signal is "XIL_INTERFACENAME TDC_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0";
begin
  DIG_AXI_OUT_0(1) <= \^fmc_c17\;
  DIG_AXI_OUT_0(0) <= \^fmc_c18\;
  DIG_DEBUG_AXI_OUT_0(31) <= \^ctrl_vb\;
  DIG_DEBUG_AXI_OUT_0(30) <= \^scn_in\;
  DIG_DEBUG_AXI_OUT_0(29) <= \^in_en\;
  DIG_DEBUG_AXI_OUT_0(28) <= \^clk_b\;
  DIG_DEBUG_AXI_OUT_0(27) <= \^clk_a\;
  DIG_DEBUG_AXI_OUT_0(26) <= \^ctrl_en\;
  DIG_DEBUG_AXI_OUT_0(25) <= \^dff_rst\;
  DIG_DEBUG_AXI_OUT_0(24) <= \^tdc_compute\;
  DIG_DEBUG_AXI_OUT_0(23) <= \^tdc_rst\;
  DIG_DEBUG_AXI_OUT_0(22) <= \^tdc_en\;
  DIG_DEBUG_AXI_OUT_0(21) <= \^vtc_en\;
  DIG_DEBUG_AXI_OUT_0(20) <= \^vdac_ctrl\;
  DIG_DEBUG_AXI_OUT_0(19) <= \^rst_cap_b\;
  DIG_DEBUG_AXI_OUT_0(18) <= \^chg_en\;
  DIG_DEBUG_AXI_OUT_0(17) <= \^bank_sel\;
  DIG_DEBUG_AXI_OUT_0(16) <= \^calib_en\;
  DIG_DEBUG_AXI_OUT_0(15) <= \^inputen_dac\;
  DIG_DEBUG_AXI_OUT_0(14 downto 11) <= \^scn_sel\(3 downto 0);
  DIG_DEBUG_AXI_OUT_0(10 downto 9) <= \^cs\(1 downto 0);
  DIG_DEBUG_AXI_OUT_0(8) <= \^write_en\;
  DIG_DEBUG_AXI_OUT_0(7) <= \^clk_sa\;
  DIG_DEBUG_AXI_OUT_0(6) <= \^bl_pchg\;
  DIG_DEBUG_AXI_OUT_0(5) <= \^sa_en\;
  DIG_DEBUG_AXI_OUT_0(4) <= \^wl_en\;
  DIG_DEBUG_AXI_OUT_0(3 downto 0) <= \^bank_en\(3 downto 0);
  DIG_DEBUG_AXI_OUT_1(1) <= \^ctrl_vbp\;
  DIG_DEBUG_AXI_OUT_1(0) <= \^ctrl_vbn\;
  FMC_B16 <= \^ctrl_vb\;
  FMC_B17 <= \^ctrl_vbp\;
  FMC_B19 <= \^rst_cap_b\;
  FMC_B20 <= \^chg_en\;
  FMC_B21 <= \^ctrl_vbn\;
  FMC_C20 <= \^clk_sa\;
  FMC_C22 <= \^scn_in\;
  FMC_D20 <= \^bl_pchg\;
  FMC_D21 <= \^sa_en\;
  FMC_D22 <= \^in_en\;
  FMC_E21 <= \^write_en\;
  FMC_F19 <= \^clk_b\;
  FMC_G19 <= \^clk_a\;
  FMC_G21 <= \^ctrl_en\;
  FMC_J18 <= \^scn_sel\(2);
  FMC_J21 <= \^dff_rst\;
  FMC_J22 <= \^tdc_compute\;
  FMC_K18 <= \^scn_sel\(3);
  FMC_K19 <= \^bank_en\(3);
  FMC_K20 <= \^inputen_dac\;
  FMC_L17 <= \^calib_en\;
  FMC_L21 <= \^wl_en\;
  FMC_L22 <= \^bank_en\(0);
  FMC_M17 <= \^bank_sel\;
  FMC_M19 <= \^vdac_ctrl\;
  FMC_M20 <= \^vtc_en\;
  FMC_N19 <= \^scn_sel\(0);
  FMC_N20 <= \^scn_sel\(1);
  FMC_N22 <= \^tdc_en\;
  FMC_P22 <= \^tdc_rst\;
  FMC_R19 <= \^bank_en\(1);
  FMC_R20 <= \^cs\(0);
  FMC_R21 <= \^cs\(1);
  FMC_T19 <= \^bank_en\(2);
  \^bank_en\(3 downto 0) <= BANK_EN(3 downto 0);
  \^bank_sel\ <= BANK_SEL;
  \^bl_pchg\ <= BL_PCHG;
  \^calib_en\ <= CALIB_EN;
  \^chg_en\ <= CHG_EN;
  \^clk_a\ <= CLK_A;
  \^clk_b\ <= CLK_B;
  \^clk_sa\ <= CLK_SA;
  \^cs\(1 downto 0) <= CS(1 downto 0);
  \^ctrl_en\ <= CTRL_EN;
  \^ctrl_vb\ <= CTRL_VB;
  \^ctrl_vbn\ <= CTRL_VBN;
  \^ctrl_vbp\ <= CTRL_VBP;
  \^dff_rst\ <= DFF_RST;
  \^fmc_c17\ <= FMC_C17;
  \^fmc_c18\ <= FMC_C18;
  \^in_en\ <= IN_EN;
  \^inputen_dac\ <= InputEN_DAC;
  \^rst_cap_b\ <= RST_CAP_B;
  \^sa_en\ <= SA_EN;
  \^scn_in\ <= SCN_IN;
  \^scn_sel\(3 downto 0) <= SCN_SEL(3 downto 0);
  \^tdc_compute\ <= TDC_COMPUTE;
  \^tdc_en\ <= TDC_EN;
  \^tdc_rst\ <= TDC_RST;
  \^vdac_ctrl\ <= VDAC_CTRL;
  \^vtc_en\ <= VTC_EN;
  \^wl_en\ <= WL_EN;
  \^write_en\ <= WRITE_EN;
  FMC_B22 <= 'Z';
  FMC_D15 <= 'Z';
  FMC_E15 <= 'Z';
  FMC_E18 <= 'Z';
  FMC_F18 <= 'Z';
  FMC_G20 <= 'Z';
end STRUCTURE;
